# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CrimeTerminator' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReactiveCocoa', '~> 4.1.0'
  pod "BWWalkthrough" 
  pod 'Alamofire', '~> 3.3'
  pod 'MBProgressHUD', '~> 0.9.2'

  # Pods for CrimeTerminator

  target 'CrimeTerminatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrimeTerminatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
